/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_skymatic_ffi_jni_PngWrapper */

#ifndef _Included_de_skymatic_ffi_jni_PngWrapper
#define _Included_de_skymatic_ffi_jni_PngWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_skymatic_ffi_jni_PngWrapper
 * Method:    getVersion0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_skymatic_ffi_jni_PngWrapper_getVersion0
  (JNIEnv *, jobject);

/*
 * Class:     de_skymatic_ffi_jni_PngWrapper
 * Method:    getDimensions0
 * Signature: (Ljava/lang/String;)Lde/skymatic/ffi/common/Dimensions;
 */
JNIEXPORT jobject JNICALL Java_de_skymatic_ffi_jni_PngWrapper_getDimensions0
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
